### ISSUE TITLE
newc format

### ISSUE THREAD

**Issue by piranna** [finnp/cpio-stream#3]
Is there's a posibility to add support for the `newc` format? Is the one used on the Linux kernel initramfs... It would be useful for NodeOS.

**Comment by finnp** [comment]
Sorry, that this took me so long, but I've now merged your work and published as `1.1.0`. Hope it's still in time for your thesis :grin:

**Comment by piranna** [comment]
Yeah, don't worry :-D It's working correctly with my GitHub account, but having it on master is cleaner. Thank you so much! :-)
